apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubedoom
  labels:
    app: my-kubedoom
  namespace: kubedoom  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-kubedoom
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - name: my-kubedoom
          image: storaxdev/kubedoom:0.5.0
          env:
            - name: NAMESPACE
              value: kubedoom
          ports:
            - containerPort: 5900
              protocol: TCP