---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postg-storage
  namespace: gb-redmine
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-ceph-ssd-gz1"